function plan = buildfile
import matlab.buildtool.Task
import matlab.buildtool.tasks.*

% Create a plan with no tasks
plan = buildplan;

% Add a task to identify and export the code issues
plan("check") = CodeIssuesTask(["toolbox", "tests"], ...
    WarningThreshold=0, ...
    Results="code-issues/results.sarif");

plan("unit") = TestTask( "tests", ...
    Description="Run MATLAB unit tests", ...
    SourceFiles="toolbox", ...
    TestResults="testResults.xml");

plan("integration") = Task( ...
    Description="Build sample toolbox dependencies with vcpkg", ...
    Inputs=["toolbox", "tests/vcpkg.json"], ...
    Outputs=[fullfile("work", vcpkg.getHostTriplet), fullfile("work", vcpkg.getTargetTriplet)], ...
    Actions={@(~) vcpkg.buildVcpkgDeps('tests', '--x-install-root=../work')});

plan("test") = Task( ...
    Description="Run all tests", ...
    Dependencies=["unit" "integration"]);

% Package toolbox
plan("package") = Task( ...
    Description="Package toolbox", ...
    Dependencies=["check" "test"], ...
    Actions={@(~, toolboxVersion) packageToolbox(erase(toolboxVersion, "v"))});

% Make check and test the default tasks in the plan
plan.DefaultTasks = ["check" "test"];

end